//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGODonationAcceptance
    {
        public int NGODonationAcceptanceId { get; set; }
        public Nullable<int> NGOId { get; set; }
        public Nullable<int> DatonationTypeId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual DonationType DonationType { get; set; }
        public virtual NGO NGO { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
